### ISSUE TITLE
hello, i use this software to download jable.tv

### ISSUE THREAD

**Issue by fifexu** [aquariusStudio/cicada#3]
hello, i use this software to download jable.tv

Thank you very much for your software, I like it very much, I have two questions I want feedback
1. I hope to update the software stability, or update the version, provide the packaged 0.2 version, and now it will lose its response after working for a long time
2. The most critical problem is that when I use it to download jable.tv, I can only open one task at the same time, and the new task must delete the previous task, which is very cumbersome, I hope it can be improved, no matter what I do Setting can't be avoided, or please tell me how to solve it, it's too annoying to only download one at a time and not keep records.
3. Some websites automatically jump to https://missav.com/, I hope to join support
Thanks again for the software, it's great

**Comment by aquariusStudio** [comment]
1. Software stability does have some problems, mainly because i use java invoke the browser, so the UI switching is very problematic, I will try to solve.  Later , I will use Chrome in 0.2 version (0.1 version is not used because Chrome is too memory intensive), the specific work is still under development, estimated to take about 2 or 3 months, the use of Chrome can be a complete solution to the stability problem (after all, many problems in IE browser, it is difficult to solve with Java).
2. I tested jable.tv myself, and there is no such problem, you can download multiple videos at the same time. If you are sure about the problem, please add more details. Please make sure the video you want to download is not a duplicate case, for the same video, it is not possible to create multiple tasks.
3.  I just took a look of the missav site,. I will release version 0.11 at the end of the month, to fix some problems and support missav.

Thanks for your issue.

**Comment by fifexu** [comment]
Thank you very much for your reply, in which I have solved problem 2 by myself, I hope you all are well
